/**
 * Ratina.ai Export Service
 * Generates downloadable sourcing artifacts from investigation data.
 * Exports use ONLY the current investigation's actual data.
 */

/**
 * Generate a plain-text Sourcing Brief from investigation data.
 */
export function generateSourcingBriefText(data) {
  if (!data) return 'No investigation data available for export.';

  const lines = [];
  const sep = '═'.repeat(60);
  const thin = '─'.repeat(60);

  lines.push(sep);
  lines.push('  RATINA SOURCING BRIEF');
  lines.push('  Generated by ratina.ai — Evidence-Based Product Intelligence');
  lines.push(sep);
  lines.push('');

  // Category & Timestamp
  lines.push(`CATEGORY: ${data.category || 'Unknown'}`);
  lines.push(`INVESTIGATION DATE: ${data.timestamp || new Date().toISOString()}`);
  lines.push(`RUN ID: ${data.executionMetadata?.runId || 'N/A'}`);
  lines.push(`EXECUTION TYPE: ${data.executionMetadata?.isLiveExecution ? 'LIVE MONID EXECUTION' : 'SAVED RESULT'}`);
  lines.push('');

  // Decision
  lines.push(thin);
  lines.push('SOURCING DECISION');
  lines.push(thin);
  const decision = data.finalDecision || {};
  lines.push(`DECISION: ${decision.decision || 'N/A'}`);
  lines.push(`EVIDENCE CONFIDENCE: ${decision.evidenceConfidence || 'N/A'}`);
  lines.push(`CONFIDENCE DETAIL: ${decision.confidenceRating || 'N/A'}`);
  lines.push('');
  lines.push(`RATIONALE:`);
  lines.push(decision.evidenceRationale || 'N/A');
  lines.push('');
  lines.push(`NEXT ACTION:`);
  lines.push(decision.nextStepAction || 'N/A');
  lines.push('');

  // Opportunity Score
  lines.push(thin);
  lines.push('PRODUCT OPPORTUNITY SCORE');
  lines.push(thin);
  const opp = data.productOpportunityScore || {};
  lines.push(`SCORE: ${opp.score || 'N/A'} / ${opp.maxScore || 100}`);
  lines.push(`FORMULA: ${opp.formula || 'N/A'}`);
  lines.push(`INTERPRETATION: ${opp.interpretation || 'N/A'}`);
  lines.push('');

  // Priority Failure Modes
  lines.push(thin);
  lines.push('PRIORITY FAILURE MODES');
  lines.push(thin);
  
  const severity = data.strictSeverityScores || [];
  severity.forEach((s, i) => {
    if (s.totalObservedMentions === 0) return;
    lines.push('');
    lines.push(`  #${i + 1} — ${s.failureMode}`);
    lines.push(`  Severity Score: ${s.severityScore}/100 (${s.severityTier})`);
    lines.push(`  Total Mentions: ${s.totalObservedMentions}`);
    lines.push(`  Safety Hazard: ${s.isSafetyHazard ? 'YES' : 'NO'}`);
    lines.push(`  Evidence: ${s.evidenceBasis}`);

    // Find matching sourcing spec
    const spec = (data.strictSourcingSpecs || []).find(sp => sp.failureMode === s.failureMode);
    if (spec) {
      lines.push(`  Priority: ${spec.priority}`);
      lines.push(`  Engineering Requirement: ${spec.engineeringRequirement}`);
      lines.push(`  QA Requirement: ${spec.qaRequirement}`);
      lines.push(`  Listing Implication: ${spec.listingImplication}`);
    }
  });
  lines.push('');

  // Competitor Summary
  lines.push(thin);
  lines.push('COMPETITOR SUMMARY');
  lines.push(thin);
  
  const competitors = data.strictCompetitorSummary || [];
  competitors.forEach((c, i) => {
    lines.push('');
    lines.push(`  ${i + 1}. ${c.name || c.asin}`);
    lines.push(`     ASIN: ${c.asin}`);
    lines.push(`     Price: ${c.livePrice || 'UNAVAILABLE'}`);
    lines.push(`     Rating: ${c.liveRating || 'N/A'}`);
    lines.push(`     Reviews Retrieved: ${c.reviewsRetrieved}`);
    lines.push(`     Data Quality: ${c.dataQualityStatus}`);

    if (c.failureCounts) {
      const failures = Object.entries(c.failureCounts).filter(([, v]) => v > 0);
      if (failures.length > 0) {
        lines.push(`     Failures: ${failures.map(([k, v]) => `${k}: ${v}`).join(', ')}`);
      } else {
        lines.push(`     Failures: None detected (see data quality status)`);
      }
    }
  });
  lines.push('');

  // Data Limitations
  lines.push(thin);
  lines.push('DATA LIMITATIONS & EVIDENCE GAPS');
  lines.push(thin);
  const lim = data.dataLimitations || {};
  if (lim.highConfidenceDataset) {
    lines.push(`High-Confidence Data: ${Array.isArray(lim.highConfidenceDataset) ? lim.highConfidenceDataset.join(', ') : lim.highConfidenceDataset}`);
  }
  if (lim.sparseDatasetNotice) {
    lines.push(`⚠ Sparse Dataset: ${lim.sparseDatasetNotice}`);
  }
  if (lim.zeroReviewNotice) {
    lines.push(`⚠ Zero Reviews: ${lim.zeroReviewNotice}`);
  }
  if (lim.failureNotice) {
    lines.push(`⚠ Retrieval Failures: ${lim.failureNotice}`);
  }
  if (lim.anomalyNotice) {
    lines.push(`⚠ Anomalies: ${lim.anomalyNotice}`);
  }
  lines.push('');

  // Open Questions
  lines.push(thin);
  lines.push('OPEN QUESTIONS / EVIDENCE GAPS');
  lines.push(thin);
  
  const sparseComps = competitors.filter(c => c.reviewsRetrieved < 5 && c.reviewsRetrieved > 0);
  const zeroComps = competitors.filter(c => c.reviewsRetrieved === 0);
  const unavailablePriceComps = competitors.filter(c => c.livePrice === 'UNAVAILABLE');

  if (sparseComps.length > 0) {
    lines.push(`- ${sparseComps.length} competitor(s) have sparse review data (<5 reviews). Deeper scraping recommended.`);
  }
  if (zeroComps.length > 0) {
    lines.push(`- ${zeroComps.length} competitor(s) returned zero reviews. Cannot assess failure patterns.`);
  }
  if (unavailablePriceComps.length > 0) {
    lines.push(`- ${unavailablePriceComps.length} competitor(s) have unavailable prices. Pricing analysis incomplete.`);
  }
  if (sparseComps.length === 0 && zeroComps.length === 0 && unavailablePriceComps.length === 0) {
    lines.push('- No critical evidence gaps identified.');
  }
  lines.push('');

  // Monid Receipt
  lines.push(thin);
  lines.push('MONID EXECUTION SUMMARY');
  lines.push(thin);
  const receipt = data.monidReceipt || {};
  lines.push(`Total Actual Cost: ${receipt.totalMonidCostUSD || 'N/A'}`);
  lines.push(`Total Calls Executed: ${receipt.totalCallsExecuted || 'N/A'}`);
  lines.push(`Successful Calls: ${receipt.successfulCalls || 'N/A'}`);
  lines.push(`Failed Calls: ${receipt.failedCalls || 0}`);
  lines.push('');
  lines.push(sep);
  lines.push('  End of Ratina Sourcing Brief');
  lines.push(sep);

  return lines.join('\n');
}

/**
 * Generate a structured JSON sourcing artifact from investigation data.
 * Preserves all fields for programmatic consumption.
 */
export function generateSourcingJSON(data) {
  if (!data) return { error: 'No investigation data available' };

  return {
    _meta: {
      format: 'ratina-sourcing-brief-v2',
      generatedAt: new Date().toISOString(),
      generator: 'ratina.ai',
      isLiveExecution: data.executionMetadata?.isLiveExecution || false,
      runId: data.executionMetadata?.runId || null,
      executedAt: data.executionMetadata?.executedAt || data.timestamp
    },
    category: data.category,
    decision: data.finalDecision,
    opportunityScore: data.productOpportunityScore,
    failureMatrix: data.strictMatrix,
    severityScores: data.strictSeverityScores,
    sourcingSpecifications: data.strictSourcingSpecs,
    competitorSummary: data.strictCompetitorSummary,
    dataLimitations: data.dataLimitations,
    monidReceipt: data.monidReceipt,
    executionMetadata: data.executionMetadata,
    ...(data.discovery ? { discovery: data.discovery } : {}),
    ...(data.failedCompetitors ? { failedCompetitors: data.failedCompetitors } : {})
  };
}
